# Generated by Django 2.0 on 2017-12-31 20:28

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True, verbose_name='UUID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Rickshaw Cargo',
                'verbose_name_plural': 'Rickshaw Cargoes',
                'db_table': 'rickshaw_cargo_table',
            },
            managers=[
                ('hold', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Rickshaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True, verbose_name='UUID')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('saved', models.BooleanField(default=False, verbose_name='Saved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Rickshaw',
                'verbose_name_plural': 'Rickshaws',
                'db_table': 'rickshaw_rickshaw_table',
            },
            managers=[
                ('wheels', django.db.models.manager.Manager()),
            ],
        ),
    ]
