# Generated by Django 2.0 on 2018-01-01 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rickshaw', '0003_auto_20171231_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='rickshaw',
            name='session',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='rickshaw',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Driver'),
        ),
    ]
