# Generated by Django 2.0 on 2018-01-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rickshaw', '0004_auto_20180101_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rickshaw',
            name='session',
            field=models.CharField(blank=True, max_length=2000, null=True, unique=True),
        ),
    ]
