# Generated by Django 2.0 on 2017-12-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rickshaw_example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
